version: 3
services:

  mongo:
    image: mongo
    ports:
      - 27017:27017

  postgres:
    image: postgres
    ports:
      - 5432:5432

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongo:27017"
    networks:
      - mongo-network

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"


  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongo:27017"
    networks:
      - mongo-network
  
  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    networks:
      - postgres-network

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

networks:
  mongo-network:
  postgres-network:
